name: isutahfull

on:
  schedule:
    - cron: '0 */4 * * *'  # post 6x a day

jobs:
  isutahfull-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: browser-actions/setup-firefox@latest 
      - run: firefox --version 
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("rtweet", "sf", "RSelenium", "devtools"), dependencies = TRUE)'
      - name: Install github packages
        run: Rscript -e 'devtools::install_github("omegahat/Rcompression"); devtools::install_github("hadley/emo")'
      - name: Create and post tweet
        run: Rscript isutahfull-tweet.R
